---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-site-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: shopping-site-pod
      labels:
        app: shopping-app
        env: dev
        color: blue
    spec:
      containers:
        - name: shopping-app-container
          image: madandevops2024/flipkartapp
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
