---
apiVersion: v1
kind: Service
metadata:
  name: shopping-site-nodeport-svc
spec:
  type: LoadBalancer
  selector:
    color: blue #Pod label which we have created under labels
  ports:
    - port: 80
      targetPort: 8080
